/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tanma
 */
import java.sql.*;
import javax.swing.JOptionPane;
public class UserIssue extends javax.swing.JFrame {

    /**
     * Creates new form UserIssue
     */
    public UserIssue() {
        initComponents();
        clrscr();
        clrbookvalid();
        bid_txt.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        sid_intTXT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        passTXT = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Std_notokLBL1 = new javax.swing.JLabel();
        Std_okLBL = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bid_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idate = new rojeru_san.componentes.RSDateChooser();
        ddate = new rojeru_san.componentes.RSDateChooser();
        jLabel5 = new javax.swing.JLabel();
        B_notokLBL = new javax.swing.JLabel();
        B_okLBL = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 786));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("ISSUE BOOK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 560, 203, 65));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookIcon.gif"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        sid_intTXT.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        sid_intTXT.setForeground(new java.awt.Color(0, 0, 204));
        sid_intTXT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sid_intTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("STUDENT ID :");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Password :");

        passTXT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passTXTActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VALIDATE CREDIENTIALS FIRST");

        jButton2.setText("VALIDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Std_notokLBL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/notavailableIcon.png"))); // NOI18N

        Std_okLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/availableIcon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sid_intTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(jButton2)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(Std_okLBL)
                                        .addGap(18, 18, 18)
                                        .addComponent(Std_notokLBL1)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(passTXT)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sid_intTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passTXT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Std_notokLBL1)
                    .addComponent(Std_okLBL))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 180, 420, 290));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        bid_txt.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        bid_txt.setForeground(new java.awt.Color(0, 0, 204));
        bid_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bid_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bid_txtFocusLost(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BOOK ID :");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ISSUE DATE :");

        idate.setForeground(new java.awt.Color(0, 0, 204));
        idate.setFuente(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        idate.setPlaceholder("Select Issue Date");

        ddate.setForeground(new java.awt.Color(0, 0, 204));
        ddate.setPlaceholder("Select Due Date");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("DUE DATE :");

        B_notokLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/notavailableIcon.png"))); // NOI18N

        B_okLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/availableIcon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(bid_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(B_okLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(B_notokLBL)
                .addGap(51, 51, 51))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ddate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bid_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(B_notokLBL)
                    .addComponent(B_okLBL))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ddate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, 340));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("ISSUE A BOOK HERE");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 385, 113));

        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 204));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backIcon.gif"))); // NOI18N
        jLabel9.setText("GO BACK");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 6, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 170, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        issue();
        new UserHomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void passTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passTXTActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        boolean m=validateCredential();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bid_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bid_txtFocusLost
        // TODO add your handling code here:
        String s1=sid_intTXT.getText();
        String s2=passTXT.getText();
        if(s1.equals("") || s2.equals("")) {
            JOptionPane.showMessageDialog(null, "First validate your id and password.");
        }
        else {
            if(validateCredential()) {
                validateBookAvailablity();
            }
            else {
                JOptionPane.showMessageDialog(null, "please enter valid STUDENT ID AND PASSWORD \n THEN ONLY YOU CAN SEARCH BOOK");
            }
        }
    }//GEN-LAST:event_bid_txtFocusLost

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        new UserHomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel4MouseClicked

    /**
     * @param args the command line arguments
     */
    private boolean validateCredential() {
        boolean b=false;
        String stdID=sid_intTXT.getText();
        int Istdid=Integer.parseInt(stdID);
        String stdpw=passTXT.getText();
        try {
            Connection con=ConnectionOP.getConnection();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from useridpw where id="+Istdid+" and password='"+stdpw+"'");
            if(rs.next()) {
                b=true;
                clrscr();
                Std_okLBL.setVisible(true);
                sid_intTXT.setEditable(false);
                passTXT.setEditable(false);
                bid_txt.setEditable(true);
                
            }
            else {
                JOptionPane.showMessageDialog(null, "INCORRECT USER ID OR PASSWORD \n PLEASE TRY AGAIN");
                Std_notokLBL1.setVisible(true);
            }
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null,"error in validating credintials");
        }
            return b;
    }
    // to check wether book is available or not
    private void validateBookAvailablity() {
        String bid=bid_txt.getText();
        try{
            Connection con=ConnectionOP.getConnection();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select availability from bookinfo where bookid='"+bid+"'");
            if(rs.next()) {
                String ctr=rs.getString(1);
                if(ctr.equals("YES")) {
                    clrbookvalid();
                    B_okLBL.setVisible(true);
                    bid_txt.setEditable(false);
                }
                else {
                    JOptionPane.showMessageDialog(null, "id is correct but book is not available");
                    B_notokLBL.setVisible(true);
                   }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "enter correct book id");
            }
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "error in validating book availability");
        }
    }
    // function to clear all book ticks and crosses 
    private void clrbookvalid() {
        B_okLBL.setVisible(false);
        B_notokLBL.setVisible(false);
    }
    // function to clear validation ticks and crosses of credentials
    private void clrscr() {
        Std_okLBL.setVisible(false);
        Std_notokLBL1.setVisible(false);
    }
    // function to clear all entries
    private void clreverything() {
        clrbookvalid();
        clrscr();
        sid_intTXT.setText("");
        passTXT.setText("");
        bid_txt.setText("");
    }
    // function to issue book
    private void issue() {
        java.util.Date aIssue=idate.getDatoFecha();
        java.util.Date aDue=ddate.getDatoFecha();
        Long l1=aIssue.getTime();
        Long l2=aDue.getTime();
        
        java.sql.Date sIssue= new java.sql.Date(l1);
        java.sql.Date sDue= new java.sql.Date(l2);
        int sid=Integer.parseInt(sid_intTXT.getText());  // student id
        String bid=bid_txt.getText(); // book id
        
        try {
            Connection con=ConnectionOP.getConnection();
            PreparedStatement pst=con.prepareStatement("insert into issuereturn (studentid,bookid,issue_date,due_date) values(?,?,?,?)");
            pst.setInt(1, sid);
            pst.setString(2, bid);
            pst.setDate(3, sIssue);
            pst.setDate(4, sDue);
            
            int affrow = pst.executeUpdate();
            
            if(affrow!=0) {
                JOptionPane.showMessageDialog(null, "CONGRATULATIONS YOU HAVE SUCCESSFULLY ISSUED A BOOK");
                NOTAVAILABLE(bid);
                clreverything();
            }
            else {
                JOptionPane.showMessageDialog(null, "NOT ISSUED");
                clreverything();
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "book already issued by you");
        }
        
    }
    //function to change availability in database
    private void NOTAVAILABLE(String bid) {
        try {
            Connection con=ConnectionOP.getConnection();
            PreparedStatement pst=con.prepareStatement("update bookinfo set availability='NO' where bookid=?");
            pst.setString(1,bid);
            int affrow=pst.executeUpdate();
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "error in updating availability");
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserIssue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserIssue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserIssue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserIssue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserIssue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel B_notokLBL;
    private javax.swing.JLabel B_okLBL;
    private javax.swing.JLabel Std_notokLBL1;
    private javax.swing.JLabel Std_okLBL;
    private javax.swing.JTextField bid_txt;
    private rojeru_san.componentes.RSDateChooser ddate;
    private rojeru_san.componentes.RSDateChooser idate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField passTXT;
    private javax.swing.JTextField sid_intTXT;
    // End of variables declaration//GEN-END:variables
}
